name = "newsnow"
type = "javascript"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"
database_id = "aed5b796-1c2c-48c0-98a8-369fc3943ef5"
